let nombre = "Luis"
let apellido = "Ayala"
let estudiante = nombre.concat(' ', apellido)
let estudianteMayus = console.log(estudiante.toUpperCase())
let estudianteMinus = console.log(estudiante.toLowerCase())
let estudianteLength = console.log(estudiante.length)
let estudianteFirst = console.log(estudiante.charAt(0))
let estudianteLast = console.log(estudiante.substr(-1))
let espacios = console.log(estudiante.trim())
let estudianteTrue = console.log(estudiante.includes("Luis"))
